apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sampleapp
    version: "1"
  name: sampleapp
  namespace: gr1
spec:
  containers:
  - image: nginx
    name: sampleapp
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: 
          - ALL
      runAsNonRoot: true
      seccompProfile:
        type: Localhost
  dnsPolicy: ClusterFirst
  restartPolicy: Always
