apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sampleapp
    version: 1
  name: sampleapp
  #namespace: gr
spec:
  containers:
  - image: nginx
    name: sampleapp
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
