apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sampleapp2
    version: "1"
  name: sampleapp2
  namespace: gr1
spec:
  containers:
  - image: alpine
    command: ["sh", "-c", "while true; do sleep 2; done"]
    name: sampleapp2
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: 
          - ALL
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
  dnsPolicy: ClusterFirst
  restartPolicy: Always
